project_id = "dxllojjazxizuylbmezc"

[functions.analisar-contrato]
verify_jwt = true

[functions.analisar-contrato-ia]
verify_jwt = true

[functions.enviar-notificacao-whatsapp]
verify_jwt = true

[functions.enviar-notificacao-email]
verify_jwt = true

[functions.enviar-valores-contrato]
verify_jwt = true

[functions.verificar-alertas]
verify_jwt = false

[functions.signature-webhook]
verify_jwt = false

[functions.enviar-solicitacao-compras]
verify_jwt = false

[functions.enviar-notificacao-financeiro]
verify_jwt = false
